### PR TITLE
Show "node" subfields for unset schema params

### PR DESCRIPTION
**Pull request by nmoroze**
This PR addresses the fact that our change to storing all value-specific data underneath the "node" dict makes the subfields not appear for unset parameters in a manifest. I fixed this by adding a `'default', 'default'` entry that is always empty and is used to initialize the node dict whenever it gets populated, mimicking the pattern that gets used for schema parameter keypaths themselves.

I was originally planning to have `'global', 'global'` be always filled in by default, but I realized this mucks with some of the logic as it loses the distinction between required and optional pernode parameters (required ones should not have a `'global', 'global'` entry).

### CODE REVIEW

**Comment by nmoroze** [comment]
Github is currently reporting service degradation for Actions, will re-run once it's restored: https://www.githubstatus.com/

**Comment by nmoroze** [comment]
@gadfort I ended up implementing what we discussed offline where the `defvalue` field gets replaced by the `value` field under `default, default`. This change actually felt pretty natural during implementation - it simplifies the code in a few places.

Although this is not what we discussed, I decided not to provide a mechanism to override the default value (but I did add a mechanism to retrieve it). Even though this technically regresses on functionality, I still think it feels a little iffy to do it in the first place, and it might be okay to not allow it unless we come up with a compelling reason to make it possible.

**Comment by gadfort** [comment]
Please update docs and resolve merge conflicts

**Review by gadfort — APPROVED** [review]
Lgtm

**Pull request merged**
