### PR TITLE
remove lib merging from yosys with new yosys version

### PR DESCRIPTION
**Pull request by gadfort**

### CODE REVIEW

**Comment by gadfort** [comment]
@sebinho FYI

**Comment by sebinho** [comment]
Thanks 
Will it be an issue if my different LIB files contain templates with the same name?

**Comment by gadfort** [comment]
@sebinho it shouldn't, if it does we would need to get that fixed in ABC. Please try it out and let me know if you have any issues.

**Comment by gadfort** [comment]
Thats great to hear.

**Pull request merged**
