### PR TITLE
add option to get report images with screenshot

### PR DESCRIPTION
**Pull request by gadfort**

### CODE REVIEW

**Review by troibe — APPROVED** [review]
Looks good to me.
Now that I think about it is there some nice way to integrate tcl scripts with the python tests we have?

**Comment by gadfort** [comment]
@troibe what do you mean about integrating tcl with python?

**Comment by troibe** [comment]
> @troibe what do you mean about integrating tcl with python?

As in adding a unit test that checks if this feature calls this tcl function.

**Comment by troibe** [comment]
Added SC-611

**Pull request merged**
