### PR TITLE
Ensure units are used in metrics and used when printing tables and reports

### PR DESCRIPTION
**Pull request by gadfort**
Changes:
- adds `_record_metric` helper function to assist tools in recording the metrics with the correct units + unit tests to check functionality
- adds `_clear_metrics` helper function to unset metrics and reports
- updates all tool drivers that use new helpers and core
- adds units modules to help with converting between units and formatting + unit tests to check functionality

Before summary():
```
                   import0        syn0       floorplan0       physyn0         place0          cts0          route0          dfm0        export0        export1
 errors               0            0              0              0              0              0              0              0             0              0
 warnings             10           75             16             0              0              2              69            235            1              0
 drvs                ---          ---             1              1              0              0              0              0            ---             0
 unconstrained       ---          ---             18             18             18             18             18             18           ---             18
 cellarea            ---         423.0         446.082        446.082        500.346        509.656        509.656        509.656         ---          509.656
 totalarea           ---          ---          6398.36        6398.36        6398.36        6398.36        6398.36        6398.36         ---          6398.36
 utilization         ---          ---         0.0697181      0.0697181      0.0781991      0.0796541      0.0796541      0.0796541        ---         0.0796541
 peakpower           ---          ---       0.000201519    0.000201519    0.000260392    0.000342972    0.000333378    0.000311837        ---       0.000339346
 leakagepower        ---          ---       8.70563e-06    8.70563e-06    1.12103e-05    1.16409e-05    1.16409e-05    1.16409e-05        ---       1.16409e-05
 holdpaths           ---          ---             0              0              0              0              0              0            ---             0
 setuppaths          ---          ---             0              0              0              0              0              0            ---             0
 holdslack           ---          ---          0.105567       0.105567        0.1073        0.111021       0.110985        0.1074         ---          0.110998
 holdwns             ---          ---            0.0            0.0            0.0            0.0            0.0            0.0           ---            0.0
 holdtns             ---          ---            0.0            0.0            0.0            0.0            0.0            0.0           ---            0.0
 setupslack          ---          ---          1.07322        1.07322         1.0778        1.07532        1.09123        1.12594         ---          1.07506
 setupwns            ---          ---            0.0            0.0            0.0            0.0            0.0            0.0           ---            0.0
 setuptns            ---          ---            0.0            0.0            0.0            0.0            0.0            0.0           ---            0.0
 fmax                ---          ---      1079010000.0   1079010000.0   1084370000.0   1081460000.0   1100390000.0   1144090000.0        ---      1081150000.0
 macros              ---          ---             0              0              0              0              0              0            ---             0
 cells               ---          261            365            365            365            370            370            370           ---            370
 registers           ---           35             35             35             35             35             35             35           ---             35
 buffers             ---          ---             22             22             22             27             27             27           ---             27
 pins                ---          ---             54             54             54             54             54             54           ---             54
 nets                ---          ---            324            324            324            329            329            329           ---            329
 vias                ---          ---            ---            ---            ---            ---            1910           ---           ---            ---
 wirelength          ---          ---            ---            ---            ---            ---           3993.0          ---           ---            ---
 memory          33488896.0   30949376.0     95158272.0     92745728.0    198651904.0    108302336.0    816685056.0    107560960.0   550764544.0    115113984.0
 exetime             0.31         0.71           0.51           0.41           1.93           2.03           5.39           0.41          1.86           0.51
 tasktime            0.45         1.78           0.84           0.76           2.28           2.35           5.72           0.72          2.33           0.83
```

After summary():
```
              units   import0      syn0   floorplan0   physyn0     place0      cts0      route0      dfm0     export0    export1
 errors                   0          0          0          0          0          0          0          0          0          0
 warnings                 10         75         16         0          0          2          69        235         1          0
 drvs                    ---        ---         1          1          0          0          0          0         ---         0
 unconstrained           ---        ---         18         18         18         18         18         18        ---         18
 cellarea       um^2     ---      423.000    446.082    446.082    500.346    509.656    509.656    509.656      ---      509.656
 totalarea      um^2     ---        ---      6398.360   6398.360   6398.360   6398.360   6398.360   6398.360     ---      6398.360
 utilization       %     ---        ---       6.972      6.972      7.820      7.965      7.965      7.965       ---       7.965
 peakpower        mw     ---        ---       0.202      0.202      0.260      0.343      0.333      0.312       ---       0.339
 leakagepower     mw     ---        ---       0.009      0.009      0.011      0.012      0.012      0.012       ---       0.012
 holdpaths               ---        ---         0          0          0          0          0          0         ---         0
 setuppaths              ---        ---         0          0          0          0          0          0         ---         0
 holdslack        ns     ---        ---       0.106      0.106      0.107      0.111      0.111      0.107       ---       0.111
 holdwns          ns     ---        ---       0.000      0.000      0.000      0.000      0.000      0.000       ---       0.000
 holdtns          ns     ---        ---       0.000      0.000      0.000      0.000      0.000      0.000       ---       0.000
 setupslack       ns     ---        ---       1.073      1.073      1.078      1.075      1.091      1.126       ---       1.075
 setupwns         ns     ---        ---       0.000      0.000      0.000      0.000      0.000      0.000       ---       0.000
 setuptns         ns     ---        ---       0.000      0.000      0.000      0.000      0.000      0.000       ---       0.000
 fmax             Hz     ---        ---       1.079G     1.079G     1.084G     1.081G     1.100G     1.144G      ---       1.081G
 macros                  ---        ---         0          0          0          0          0          0         ---         0
 cells                   ---        261        365        365        365        370        370        370        ---        370
 registers               ---         35         35         35         35         35         35         35        ---         35
 buffers                 ---        ---         22         22         22         27         27         27        ---         27
 pins                    ---        ---         54         54         54         54         54         54        ---         54
 nets                    ---        ---        324        324        324        329        329        329        ---        329
 vias                    ---        ---        ---        ---        ---        ---        1910       ---        ---        ---
 wirelength       um     ---        ---        ---        ---        ---        ---      3993.000     ---        ---        ---
 memory            B   31.770M    29.551M    90.246M    87.047M    117.770M   103.016M   764.816M   100.527M   525.039M   109.910M
 exetime                00.300     00.710     00.510     00.410     01.730     01.929     05.940     00.410     01.860     00.510
 tasktime               00.420     01.580     00.790     00.710     02.000     02.209     06.230     00.710     02.299     00.830
```

### CODE REVIEW

**Review by aulihant — COMMENTED** [review]
Nice! Much cleaner and looks as expected when I tested it out with your branch! 🙂 

Just one question - the output png now has the frequency in GHz (so my output says `Fmax: 0.219GHz` ) - not a big deal to me, but want to make sure it's expected.

**Comment by gadfort** [comment]
> Nice! Much cleaner and looks as expected when I tested it out with your branch! 🙂
> 
> Just one question - the output png now has the frequency in GHz (so my output says `Fmax: 0.219GHz` ) - not a big deal to me, but want to make sure it's expected.

Oops, no, it shouldn't, I'll take a look

**Comment by gadfort** [comment]
@aulihant was on an old branch: this is the correct image from heartbeat
heartbeat

**Review by aulihant — APPROVED** [review]
Confirmed that I see the same format as what Peter shared with the latest branch. 

LGTM!

**Review by nmoroze — APPROVED** [review]
Looks good to me! Great change.

One thing to be aware of: we had been intentionally setting the reports in `setup()` since most schema modifications in `post_process()` get dropped, but it's a somewhat unintentional side effect of #1162 that setting them in `post_process()` works now. I think it's a lot easier/clearer from a tool driver author perspective to store the source alongside setting the metric, but we just need to be mindful that we've decided it's "legal" to set this keypath in `post_process()` going forward and not regress on that.

**Comment by gadfort** [comment]
@nmoroze I added to the test_openroad.py a check to ensure the report and metric is set as a guard against regressing on that

**Comment by aolofsson** [comment]
This is awesome!

**Review by aolofsson — APPROVED** [review]

**Pull request merged**
