### PR TITLE
Implement 'env' schema parameter

### PR DESCRIPTION
**Pull request by nmoroze**
This PR adds functionality for 'env' parameter + a test for it.

### CODE REVIEW

**Comment by aolofsson** [comment]
Not sure this is the right place for it? Shouldn't it be in the _runtask so that it gets set on the compute node?

**Comment by nmoroze** [comment]
I thought a bit about this, I think this works since compute nodes will re-enter SC through run(), and the parent environment will get propagated into the child processes that run _runtask() (the test verifies this). 

Benefit of putting this in run() is that it calls check_manifest(), which could potentially resolve on env vars being set to resolve file paths in some of the checks.

**Comment by nmoroze** [comment]
> I thought a bit about this, I think this works since compute nodes will re-enter SC through run(), and the parent environment will get propagated into the child processes that run _runtask() (the test verifies this).

Although I could be wrong about this if there's some sort of more complex setup I'm not foreseeing. cc @WRansohoff, does this seem alright to you?

**Comment by WRansohoff** [comment]
This seems like a reasonable place for it; the `Chip.run()` method still gets called on the compute nodes. They determine which task to run from the `-arg_step`/`-arg_index` parameters, and load their `active`/`error` flags from the parent's configuration.

My only comment is that the 'env' parameter shouldn't be allowed through the remote schema sanitizer; we don't want to accidentally overwrite a $PATH variable or something like that.

**Comment by aolofsson** [comment]
You are both right. The re-entrant sc got me again.:-)

**Review by aolofsson — APPROVED** [review]

**Pull request merged**
