### PR TITLE
Update documentation with remote response formats

### PR DESCRIPTION
**Pull request by WRansohoff**
Add lists of possible response formats to the server API reference manual, and fix an old reference to `sc-ping`.

### CODE REVIEW

**Comment by gadfort** [comment]
@WRansohoff can the responses be better formatted in the docs? right now it's just showing the json format which is not very easy to read.

**Comment by WRansohoff** [comment]
Maybe. I spent about an hour trying to get the table to render multiple lines without success, but I can keep looking.

**Comment by gadfort** [comment]
@WRansohoff any updates on this?

**Comment by WRansohoff** [comment]
Sorry, I got sidetracked with the release - I haven't found a way to split the table cells into rows using docutils, so I'll probably try to find another way to format the data.

**Comment by gadfort** [comment]
@WRansohoff please do so we can get this merged.

**Comment by WRansohoff** [comment]
Alright, I finally found something that looks nice - there's a `literal_block` node which overrides the table cell's lack of line break support.

Besides the quirk of needing to pass in the text that you want to render twice, it works great.

**Review by gadfort — APPROVED** [review]

**Pull request merged**
