### PR TITLE
docs: switch to use setup() or module for documentation

### PR DESCRIPTION
**Pull request by gadfort**
Changes:
- uses `setup()` instead of `make_docs()` for documentation + associated changes in tools/pdks/libs/checklists/flows

Note:
- This is a step towards making `make_docs()` or a similar function optional

### CODE REVIEW

**Comment by aolofsson** [comment]
Looks good, but why not just remove make_docs?

**Comment by gadfort** [comment]
@aolofsson I decided to do that in a separate PR. Some of the tools/flows need the `Chip` object to contain some information, so for those, we'll need to have a way to configure the `Chip`.

**Review by nmoroze — APPROVED** [review]
Looks good, thanks!

**Review by aolofsson — APPROVED** [review]
LG!

**Pull request merged**
