### PR TITLE
wrap tarfile.read with try/except in the event of error

### PR DESCRIPTION
**Pull request by gadfort**

### CODE REVIEW

**Comment by gadfort** [comment]
@WRansohoff just checking in on this

**Review by WRansohoff — APPROVED** [review]
I made a similar change in the `('option', 'resume')` PR draft that we ended up punting on. The function should return in the event of an extraction error, and do the `os.remove` call in a `finally:` block so that it doesn't stick around on the user's system.

Should be good to go with the fixes I just committed, once we see that the CI tests pass.

**Review by WRansohoff — CHANGES_REQUESTED** [review]
Don't call 'return' in the 'finally' block - that will prevent the following logic from running when the extraction succeeds.

**Comment by gadfort** [comment]
I removed the finally block since calling return prevents finally from executing

**Comment by WRansohoff** [comment]
I don't think that's right - try running this in a REPL:

```
def abc():
   print('a')
   try:
     raise ValueError('b')
   except:
     return
   finally:
     print('b')
```

Note that both print statement execute. `finally:` blocks get run before the exception logic.

**Review by WRansohoff — APPROVED** [review]
Thanks - I know the syntax is a little confusing, a block called "finally" sounds like it would happen after everything else. It's a useful feature to keep in mind for cleanup logic, though.

**Pull request merged**
