### PR TITLE
Add an initial Dockerfile and setup script

### PR DESCRIPTION
**Pull request by WRansohoff**
This PR adds a simple Dockerfile for an Ubuntu 20.04 image with sc and the core open-source EDA tools installed.

Next steps: X11 forwarding isn't set up for GUI apps like KLayout yet, and it might be a good idea to add instructions for mounting local directories in the container.

### CODE REVIEW

**Comment by aolofsson** [comment]
Very cool. Is this complete? What about yosys?

**Comment by WRansohoff** [comment]
It is complete in the sense that it can run the entire ASIC flow and generate a GDS file, but `sc-show` won't open the design in KLayout because the container isn't configured to forward X11 windows to the host. As a workaround, we can copy the build directory out of the container with a command like:

    docker cp my_sc_container:/siliconcompiler/build/ .

And the OpenROAD-flow-scripts repository includes yosys as a submodule, so that gets installed by `install-openroad.sh`.

**Comment by aolofsson** [comment]
Got it, thanks! I forgot that openroad installs yosys as well. Apoligies for my confusion.:-)

**Review by aolofsson — APPROVED** [review]

**Comment by umarcor** [comment]
With regard to X11, I suggest to have a look at [hdl.github.io/containers: Tools with GUI](https://hdl.github.io/containers/ug/GUI.html).

**Pull request merged**
