### PR TITLE
allow overwriting the HTML report, while preventing repeat generating the result png

### PR DESCRIPTION
**Pull request by gadfort**
Fixes:
- server fails to generate HTML report correctly because its already generated in an earlier step.

### CODE REVIEW

**Comment by WRansohoff** [comment]
I'm not sure about this one - it adds a dependency on another file from the build.

Although, if we're okay with re-generating the HTML, it also seems like it would be okay to re-generate the summary PNG. Either way, it's a bit of duplicate work that doesn't need to be performed.

**Comment by nmoroze** [comment]
What's the context for this one? Not sure I understand the problem this is solving.

**Comment by gadfort** [comment]
@nmoroze @WRansohoff updated PR to come...

**Comment by gadfort** [comment]
@WRansohoff @nmoroze this restores the functionality that was there before. The only thing a user may not be able to do is regenerate the GDS->PNG step which is not required with the changes to klayout/export

**Review by nmoroze — APPROVED** [review]
Looks good, could you just update the docstring before merging? Github won't let me comment on it, but the `generate_html` and `generate_report` args say the corresponding item won't be regenerated if it already exists.

**Pull request merged**
